import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import NavItem from "@/components/NavItem";
import Image from "next/image";







const montserrat =Nunito({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-pink-200`}>
        <nav className="w-full pt-8 px-8  flex items-center justify-between bg-pink-300">
          <Image 
          src='/logo-transparent-svg.svg'
          width={200}
          height={700}
          alt="Logo"
       
          />
          <ul className="flex items-center gap-8 text-xl text-pink-900">
            <NavItem href="/">Home</NavItem>
            <NavItem href="/about">About me</NavItem>
            <NavItem href="/projects">My projects</NavItem>
            <NavItem href="/contact">Contacts</NavItem>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}